services:
  - type: web
    name: plausible
    env: docker
    plan: free           # or your chosen plan
    dockerFilePath: Dockerfile
    dockerCommand: >
      bash -lc "echo → DATABASE_URL is $DATABASE_URL && bin/plausible start"
